import calculadora
a = int(input())
b = int(input())
print("SOMA")
print(calculadora.soma(a,b))
print("SUBTRAÇÃO")
print(calculadora.subtracao(a,b))
print("MULTIPLICAÇÃO")
print(calculadora.multiplicacao(a,b))
print("DIVISÃO")
print(calculadora.divisao(a,b))
print("FATORIAL DO PRIMEIRO")
print(calculadora.fatorial(a))
print("FATORIAL DO SEGUNDO")
print(calculadora.fatorial(b))
